name: kakoune
version: "v2020.01.16"
summary: Modal editor 
description: |
  Kakoune is a code editor that implements Vi’s "keystrokes as a text editing language" model. As it’s also a modal editor, it is somewhat similar to the Vim editor (after which Kakoune was originally inspired).

  Kakoune can operate in two modes, normal and insertion. In insertion mode, keys are directly inserted into the current buffer. In normal mode, keys are used to manipulate the current selection and to enter insertion mode.

  Kakoune has a strong focus on interactivity, most commands provide immediate and incremental results, while still being competitive (as in keystroke count) with Vim.

  Kakoune works on selections, which are oriented, inclusive range of characters, selections have an anchor and a cursor character. Most commands move both of them, except when extending selection where the anchor character stays fixed and the cursor one moves around.

  See http://vimeo.com/82711574

  Join us on freenode IRC #Kakoune

  This snap is built via the build.snapcraft.io service from the
  snapcraft.yaml definition at https://github.com/lukewh/kakuone-snap to
  ensure source and build transparency.

base: core18
confinement: classic

parts:
  kakoune:
    source: https://github.com/mawww/kakoune.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-subdir: src
    build-packages:
      - libncursesw5-dev
      - pkg-config
    plugin: make

apps:
  kakoune:
    command: usr/local/bin/kak
